/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gina' at '26/2/16 12:18 PM' with Gradle 2.6
 *
 * @author gina, @date 26/2/16 12:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
    	System.out.println("Good Morning....7819 ");
    	System.out.println("World!!!!");
        return true;
    }
}
